---
# See https://pre-commit.com for more information
default_language_version:
  python: python3.12

# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args:
          - '--maxkb=1024'
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - '--fix=lf'
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    - id: ruff-format
    - id: ruff
      args:
        - '--fix'
        - '--exit-non-zero-on-fix'
